// Automatically generated by astro-icon
// 26c78b3533e819a8cabac50ff0f1a8ed64fde03981d512efc95c1a661f06f586

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fedi"
		| "kofi"
		| "linktree"
		| "rss"
		| "youtube";
}