// Automatically generated by astro-icon
// 058f0f73adf5ba88ab0628fb9d83b35e4abe2ddc59d1e9ec1d2b516bee9ce857

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fedi"
		| "kofi"
		| "linktree"
		| "youtube";
}